apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: app-cluster
data:
  server.properties: |
    process.roles=broker,controller
    node.id=${KAFKA_NODE_ID}

    controller.quorum.voters=0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093,2@kafka-2.kafka-headless:9093

    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://${POD_NAME}.kafka-headless:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT

    log.dirs=/var/lib/kafka/data
    num.partitions=3
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    min.insync.replicas=2

    group.initial.rebalance.delay.ms=0
