# k8s/apps/producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: app-cluster
  labels:
    app: consumer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer
          image: localhost/consumer-app:latest
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-0.kafka-headless.app-cluster.svc.cluster.local:9092,kafka-1.kafka-headless.app-cluster.svc.cluster.local:9092,kafka-2.kafka-headless.app-cluster.svc.cluster.local:9092"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
