# k8s/apps/producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-app
  namespace: app-cluster
  labels:
    app: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      labels:
        app: producer-app
    spec:
      containers:
        - name: producer
          image: localhost/producer-app:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
